// <auto-generated />
namespace KullaniciOtomasyon2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Version11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version11));
        
        string IMigrationMetadata.Id
        {
            get { return "202306030907594_Version.1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
