//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceOrnek
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personel", Namespace="http://tempuri.org/")]
    public partial class Personel : object
    {
        
        private string IDField;
        
        private string AdiField;
        
        private string SoyadField;
        
        private System.DateTime DTarihField;
        
        private int MaasField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Adi
        {
            get
            {
                return this.AdiField;
            }
            set
            {
                this.AdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DTarih
        {
            get
            {
                return this.DTarihField;
            }
            set
            {
                this.DTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Maas
        {
            get
            {
                return this.MaasField;
            }
            set
            {
                this.MaasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParaBirimi", Namespace="http://tempuri.org/")]
    public partial class ParaBirimi : object
    {
        
        private string IsimField;
        
        private string CurrencyNameField;
        
        private string ForexBuyingField;
        
        private string ForexSellingField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Isim
        {
            get
            {
                return this.IsimField;
            }
            set
            {
                this.IsimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CurrencyName
        {
            get
            {
                return this.CurrencyNameField;
            }
            set
            {
                this.CurrencyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ForexBuying
        {
            get
            {
                return this.ForexBuyingField;
            }
            set
            {
                this.ForexBuyingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ForexSelling
        {
            get
            {
                return this.ForexSellingField;
            }
            set
            {
                this.ForexSellingField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceOrnek.WebServiceOrnekSoap")]
    public interface WebServiceOrnekSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceOrnek.HelloWorldResponse> HelloWorldAsync(ServiceReferenceOrnek.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Topla", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ToplaAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersonelGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceOrnek.PersonelGetirResponse> PersonelGetirAsync(ServiceReferenceOrnek.PersonelGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KurGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceOrnek.KurGetirResponse> KurGetirAsync(ServiceReferenceOrnek.KurGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceOrnek.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(ServiceReferenceOrnek.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceOrnek.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(ServiceReferenceOrnek.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersonelGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersonelGetir", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceOrnek.PersonelGetirRequestBody Body;
        
        public PersonelGetirRequest()
        {
        }
        
        public PersonelGetirRequest(ServiceReferenceOrnek.PersonelGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PersonelGetirRequestBody
    {
        
        public PersonelGetirRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersonelGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersonelGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceOrnek.PersonelGetirResponseBody Body;
        
        public PersonelGetirResponse()
        {
        }
        
        public PersonelGetirResponse(ServiceReferenceOrnek.PersonelGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonelGetirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceOrnek.Personel> PersonelGetirResult;
        
        public PersonelGetirResponseBody()
        {
        }
        
        public PersonelGetirResponseBody(System.Collections.Generic.List<ServiceReferenceOrnek.Personel> PersonelGetirResult)
        {
            this.PersonelGetirResult = PersonelGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KurGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KurGetir", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceOrnek.KurGetirRequestBody Body;
        
        public KurGetirRequest()
        {
        }
        
        public KurGetirRequest(ServiceReferenceOrnek.KurGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class KurGetirRequestBody
    {
        
        public KurGetirRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KurGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KurGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceOrnek.KurGetirResponseBody Body;
        
        public KurGetirResponse()
        {
        }
        
        public KurGetirResponse(ServiceReferenceOrnek.KurGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KurGetirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReferenceOrnek.ParaBirimi> KurGetirResult;
        
        public KurGetirResponseBody()
        {
        }
        
        public KurGetirResponseBody(System.Collections.Generic.List<ServiceReferenceOrnek.ParaBirimi> KurGetirResult)
        {
            this.KurGetirResult = KurGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WebServiceOrnekSoapChannel : ServiceReferenceOrnek.WebServiceOrnekSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WebServiceOrnekSoapClient : System.ServiceModel.ClientBase<ServiceReferenceOrnek.WebServiceOrnekSoap>, ServiceReferenceOrnek.WebServiceOrnekSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceOrnekSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceOrnekSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceOrnekSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceOrnekSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceOrnekSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceOrnekSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceOrnekSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceOrnekSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceOrnek.HelloWorldResponse> ServiceReferenceOrnek.WebServiceOrnekSoap.HelloWorldAsync(ServiceReferenceOrnek.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceOrnek.HelloWorldResponse> HelloWorldAsync()
        {
            ServiceReferenceOrnek.HelloWorldRequest inValue = new ServiceReferenceOrnek.HelloWorldRequest();
            inValue.Body = new ServiceReferenceOrnek.HelloWorldRequestBody();
            return ((ServiceReferenceOrnek.WebServiceOrnekSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> ToplaAsync(int x, int y)
        {
            return base.Channel.ToplaAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceOrnek.PersonelGetirResponse> ServiceReferenceOrnek.WebServiceOrnekSoap.PersonelGetirAsync(ServiceReferenceOrnek.PersonelGetirRequest request)
        {
            return base.Channel.PersonelGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceOrnek.PersonelGetirResponse> PersonelGetirAsync()
        {
            ServiceReferenceOrnek.PersonelGetirRequest inValue = new ServiceReferenceOrnek.PersonelGetirRequest();
            inValue.Body = new ServiceReferenceOrnek.PersonelGetirRequestBody();
            return ((ServiceReferenceOrnek.WebServiceOrnekSoap)(this)).PersonelGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceOrnek.KurGetirResponse> ServiceReferenceOrnek.WebServiceOrnekSoap.KurGetirAsync(ServiceReferenceOrnek.KurGetirRequest request)
        {
            return base.Channel.KurGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceOrnek.KurGetirResponse> KurGetirAsync()
        {
            ServiceReferenceOrnek.KurGetirRequest inValue = new ServiceReferenceOrnek.KurGetirRequest();
            inValue.Body = new ServiceReferenceOrnek.KurGetirRequestBody();
            return ((ServiceReferenceOrnek.WebServiceOrnekSoap)(this)).KurGetirAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceOrnekSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceOrnekSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceOrnekSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:59785/WebServiceOrnek.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceOrnekSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:59785/WebServiceOrnek.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceOrnekSoap,
            
            WebServiceOrnekSoap12,
        }
    }
}
